### ISSUE TITLE
IDE - Initial Project view 

### ISSUE THREAD

**Issue by farmaazon** [luna/ide#141]
### Summary
Make a basic IDE application stub. It should display an Text Editor on the screen.

### Value
This is a first step for implementing IDE

### Specification
The code composition should reflect the description in _IDE Composition doc_: The Text Editor should be a part of more general Project View.
Although the views are not yet integrated with any controller, they should have some predicted way to communicate with controller.
IDE should use BaseGL for rendering. TextEditor should use TextField from that library.

### Acceptance Criteria & Test Cases
The IDE application is able to run and display TextEditor

**Comment by notdanilo** [comment]
@farmaazon this task needs more details. We still need to determine how the components communication is going to happen.

**Comment by farmaazon** [comment]
The design of component communication is a part of this task actually. Please cooperate with @mwu-tow to make the common solution for views and components.

**Comment by mwu-tow** [comment]
Perhaps this task can be split between the:
1) creating the panel that displays text editor (filled e.g. with hardcoded text);
2) providing API endpoints that allow integration with controllers.

Only the latter requires communication design, I believe that part 1 can be started with no additional requirements.

As for 2 — we will need to agree to some communication pattern, but first I'd like to spend some more time on exploring design space here. While previously I was proposing an actor-style asynchronous design, having thought that out over the weekend, now I have my doubts and I want to reconsider simpler approaches as well.
I want to come with more specific use-cases and propositions and then let's discuss this together.
