### ISSUE TITLE
Explain AST to the team.

### ISSUE THREAD

**Issue by farmaazon** [luna/ide#192]
### Summary
@mwu-tow has a significant knowledge how the Enso AST works, it should be shared to us to be able to efficiently help him in implementing Double Representation.

### Value
Knowledge is power.

### Specification
Probably done by setting up the call.

### Acceptance Criteria & Test Cases
Notes or recording from the call.

**Comment by mwu-tow** [comment]
Done.

Presentation (with drawings) [Introduction to AST.pptx](https://github.com/luna/ide/files/4256752/Introduction.to.AST.pptx)

Please note that this more of a help for presentation (not being strictly correct, taking shortcuts for some explanations) and has some known issues. It is not documentation, rather help for participants to be able to return to slides and check some things.
