### ISSUE TITLE
Adding ID to Line and making it proper AST node

### ISSUE THREAD

**Issue by mwu-tow** [luna/ide#197]

**Comment by kustosz** [comment]
@mwu-tow please keep in mind, that in order for the language server to be able to understand these IDs and send meaningful result visualizations, the id needs to be attached to the expression being inspected, not the whole line. I.e. if the line is `foo = bar + 1`, only the `bar + 1` should be marked. The reason for this is that as we discussed previously, these IDs can be attached to arbitrary expressions, e.g. function arguments (i.e. we provide the ability to just attach id to `bar` in the above example). That means the language server just blindly returns the value of the identified expression, which for assignments is always `Unit`, not the rhs value.
