### ISSUE TITLE
Implement TextField's set_size

### ISSUE THREAD

**Issue by notdanilo** [luna/ide#217]
### Summary
We need TextField to be resizeable in order to integrate with IDE.

### Value
* Resizeable TextField

### Specification
* Implement `pub fn set_size(&mut self, size:Vector2<f32>)`

### Acceptance Criteria & Test Cases
A working example.

**Comment by farmaazon** [comment]
Duplicated with https://app.zenhub.com/workspaces/enso-5b57093c92e09f0d21193695/issues/luna/ide/177
