### ISSUE TITLE
It is not possible to rescale Enso Studio window with top window edge

### ISSUE THREAD

**Issue by sylwiabr** [luna/ide#243]
### General Summary

Rescaling the window is possible just by "catching" bottom or side edges. Top edge is inactive.
### Steps to Reproduce

Open Enso Studio
Try to rescale window by grabbing the top edge
### Expected Result

Rescaled Enso Studio window
### Actual Result

Nothing happens

**Comment by BinarySoftware** [comment]
@sylwiabr Weird, i was looking into this issue, built dist from latest commit on master and everything works, every corner, every edge, could you check that again? I couldnt at least reproduce this behaviour

**Comment by wdanilo** [comment]
I cannot reproduce it on my end as well. In today's build, there will be a new option `--info`. Please provide me the output of it if it will still not work on your side.

**Comment by wdanilo** [comment]
It works on Sylwia system now. Closing.

**Comment by sylwiabr** [comment]
Working on master
