### ISSUE TITLE
Enso Studio icon not visible in macOS finder

### ISSUE THREAD

**Issue by sylwiabr** [luna/ide#248]
### Summary

<img width="233" alt="Zrzut ekranu 2020-03-9 o 13 44 18" src="https://user-images.githubusercontent.com/12892578/76214252-a1172680-620c-11ea-8bd0-9cb0fa4cad7f.png">
We should consider changing Mac OS application icon
### Value

Visible application icon
### Acceptance Criteria & Test Cases

the icon that is easy to see

**Comment by BinarySoftware** [comment]
It can change automatically depending on if the computer uses dark mode or normal mode - on dark mode white icon looks good, but on normal it should be black

**Comment by wdanilo** [comment]
@BinarySoftware do you have any sources telling that macos is able to switch icons in dark mode? I think there is no such option. Icons are the same, am I wrong?

**Comment by BinarySoftware** [comment]
@wdanilo Huh, i think you're right. i looked at https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/ at `Images, Icons, and Glyphs` section, and it said that you can specify special icon for dark and light mode, but it is about in-app icon, not the app icon. Huh, i thought macOS was a bit more advanced
