### ISSUE TITLE
PageUp/PageDown does not work as expected on short text in Text Editor.

### ISSUE THREAD

**Issue by sylwiabr** [luna/ide#280]
### General Summary

When PageUp/PageDown is used on a short text it should go to the beginning/end of the text not change the view.
### Steps to Reproduce

open the text editor 
write `def foo`
press page up
### Expected Result

cursor at the beginning of the text
### Actual Result

clean screen
### Enso Version

core     : 2.0.0-alpha.0
build    : 6d3fe64
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by notdanilo** [comment]
TextField still doesn't implement `set_size`. What's happening right now is that `TextField` is positioned to occupy half of the view bottom, while it's size is the whole view height. So what you are seeing is page up and down which is moving the whole view's height.

**Comment by notdanilo** [comment]
It should be automatically fixed when `set_size` is implemented.

**Comment by farmaazon** [comment]
But now I see, that PageUp/PageDown works wrong, because it does only scrolling, and in fact pageUp/Down should _move_ cursor, not only do scroll.

I missed it in my review, so this should be fixed
