### ISSUE TITLE
File Manager Client

### ISSUE THREAD

**Issue by notdanilo** [luna/ide#300]
### Summary
We want to get rid of our mock server and use the actual File Manager service.

### Value
File operations on the actual service.

### Specification
We want to support file read and write operations in the File Manager service. The API was slightly changed, so the RPC code needs to be updated.

Reference: https://github.com/luna/enso/blob/master/doc/design/engine/engine-services.md#file-management-operations

### Acceptance Criteria & Test Cases
1. Working example
2. Test with mock client

**Comment by sylwiabr** [comment]
Why we are testing it with a mock client if they are already implemented on engine side?

**Comment by notdanilo** [comment]
@sylwiabr I think this question was already answered, but just for the record: we need to test it on the Rust side.
