### ISSUE TITLE
The cursor over node editor is not visible and it is impossible to manipulate nodes

### ISSUE THREAD

**Issue by sylwiabr** [luna/ide#396]
### General Summary

The IDE has two parts: node and text editor. When I am moving mouse over node editor it appears above the IDE window. It is impossible to focus on node editor, manipulate nodes etc.
### Steps to Reproduce

Open IDE and try to click on node editor. Then add 
```
main = 
    2+2 
```
and try to move/select node
### Expected Result

visible cursor, ability to move and select nodes
### Actual Result

no mouse events in node editor
### Enso Version

core     : 2.0.0-alpha.0
build    : e490422
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by sylwiabr** [comment]
Additional comment: The issue is when you resize the window. Another part of it is:
After resize if you move the mouse from the area where is IDE window to the left it is appearing at the screen higher than it was. 
![2020-04-30](https://user-images.githubusercontent.com/12892578/80718008-e1eb3780-8af9-11ea-84eb-a6fdfefe94c6.jpg)

**Comment by wdanilo** [comment]
Should be part of https://github.com/luna/ide/issues/523
