### ISSUE TITLE
Selecting nodes does not work well in IDE

### ISSUE THREAD

**Issue by sylwiabr** [luna/ide#405]
### General Summary

Selecting nodes is really important feature allowing working with node editor. In IDE it is not working well.
### Steps to Reproduce

add a few nodes in IDE:
```
main = 
    4
    foo
    3+4
```
try to select with rectangle - it doesn't select nodes
try to select two nodes with `command` - there is no multiselect, the selection change to the last selected node
select first node, change focus on text editor, click on the second node - you will get two nodes selected
### Expected Result

Properly working selections of nodes
### Actual Result

As described above.
### Enso Version

core     : 2.0.0-alpha.0
build    : 86856b6
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by wdanilo** [comment]
- `try to select with rectangle - it doesn't select nodes` - duplicate: https://github.com/luna/ide/issues/479
- `select first node, change focus on text editor ...` - duplicate: https://github.com/luna/ide/issues/523
- `there is no multiselect` - to be confirmed in current version @sylwiabr

**Comment by sylwiabr** [comment]
for the current version selecting nodes with `command` works so as the rest of the issue is duplicates I am closing this one.
