### ISSUE TITLE
Issues with keyboard input after connecting nodes

### ISSUE THREAD

**Issue by joenash** [luna/ide#513]
### General Summary
Under certain situations, connecting nodes results in problems with keyboard input in the textual representation. These issues are:
- Area of text input does not match position of cursor.
- No text input is impossible. 

The factors affecting which behaviour is seen seem to be:
- Order of lines of code.
- Length of code of nodes being connected.

### Steps to Reproduce
Disable keyboard input:
- Define a node with `IO.println "hello"`
- Underneath that definition, define a node with a short string, i.e. `foo = bar`
- Connect `foo` to the port on `IO.println`, replacing `hello`. 
- Congratulations, you've turned off your keyboard.

Cursor position error.
- Define a node with `hello = IO.println "hello"`
- Underneath that definition, define a node with a long string, i.e. `foo = The quick brown fox jumps over the lazy dog`
- Connect `foo` to the port on `IO.println`, replacing `hello`. 

![](https://cdn.discordapp.com/attachments/407883082310352928/717366695072628806/2020-06-02_14.56.39.gif)

![](https://cdn.discordapp.com/attachments/407883082310352928/717366706921668699/2020-06-02_14.59.30.gif)

### Expected Result
The ports are connected, and text input works as normal. 

### Actual Result
- The order of the code will be changed. The line defining `foo` will be moved to before the line defining `hello`.
- Text input issue occurs as described above.

### Enso Version
core     : 2.0.0-alpha.0
build    : 60cedc4
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by mwu-tow** [comment]
Reduced repro:
```
0. start project with ```main = IO.println "Hello, World!"```
0. using searcher add node `"foo"`
0. using text editor change `"foo"` into `"foo2"`
0. connect `"foo2"` output as the `IO.println` argument (replacing `"Hello, World!"`)

Seemingly all this steps are necessary. Other factors (like string length) don't play any role.
After this setup this fails:
0. using text attempt editing the now-second main line (e.g. change `println` to `println2`

The text editor enters state where editing latter line is broken. Interestingly, moving cursor to the first line and editing it seems to resolve the issue.
Also, this can trigger panic -- in such case editor will be unrecoverably broken.
