### ISSUE TITLE
Cursor navigation

### ISSUE THREAD

**Issue by farmaazon** [luna/ide#71]
- Moving left/right (arrows),
- Jumping to absolute position (mouse click),
- Jumping to begin/end of line (Home, End)
- Jumping to begin/end of whole text (Ctrl+Home, Ctrl+End)
And all above operations with selecting jumped fragment (as above with Shift).

**Comment by sylwiabr** [comment]
Jumping does not work on MacOS

**Comment by sylwiabr** [comment]
Missing documentation for keyboard shortcuts

**Comment by sylwiabr** [comment]
ok, the shortcuts works, just select is crashing on Windows but there is new issue for that
